name: ooi-cgsn-adcp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - xarray
  - scipy
  - matplotlib
  - h5netcdf
  - netcdf4
  - pyyaml
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - ooi-data-explorations